force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A player for our shoot the moon app</description>
    <label>Player</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The player&#39;s current score</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/STM_ScoreboardController.cls
public with sharing class STM_ScoreboardController {
    @AuraEnabled(Cacheable=true)
    public static List<Player__c> getPlayers(){
        return [SELECT Contact__r.Name, Score__c FROM Player__c WHERE Active__c = TRUE ORDER BY Score__c DESC];
    }
    @AuraEnabled
    public static void savePlayers(List<Player__c> players){
        try{
            update players;
        }
        catch(DmlException ex){
            throw new AuraHandledException('Exception: ' + ex.getMessage());
        }
    }
}